### ISSUE TITLE
HorizontalPodAutoscaler is not showing in Deployment's details page

### ISSUE THREAD

**Issue by hossainemruz** [kmodules/resource-metadata#101]
![image](https://user-images.githubusercontent.com/12577390/115862320-d3f29d00-a455-11eb-8647-f42055877a3d.png)

**Resource Descriptor:**
```yaml
apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: autoscaling
    k8s.io/kind: HorizontalPodAutoscaler
    k8s.io/resource: horizontalpodautoscalers
    k8s.io/version: v1
  name: autoscaling-v1-horizontalpodautoscalers
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/autoscaling/horizontalpodautoscalers.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/autoscaling/horizontalpodautoscalers.png
    type: image/png
  resource:
    group: autoscaling
    kind: HorizontalPodAutoscaler
    name: horizontalpodautoscalers
    scope: Namespaced
    version: v1
  connections:
    - namespacePath: metadata.namespace
      references:
        - '{.metadata.namespace},{.spec.scaleTargetRef.apiVersion},{.spec.scaleTargetRef.kind},{.spec.scaleTargetRef.name}'
      target:
        apiVersion: apps/v1
        kind: Deployment
      type: MatchRef
  columns:
    - name: Name
      pathTemplate: '{{ jp "{.metadata.name}" . }}'
      priority: 3
      type: string
    - name: Namespace
      pathTemplate: '{{ jp "{.metadata.namespace}" . }}'
      priority: 3
      type: string
    - name: Reference
      pathTemplate: '{{ jp "{.spec.scaleTargetRef.kind}/{.spec.scaleTargetRef.name}" . }}'
      priority: 3
      type: string
    - name: Target CPU Utilization
      pathTemplate: '{{ jp "{.spec.targetCPUUtilizationPercentage}" . }}%'
      priority: 3
      type: string
    - name: Min-Replica(s)
      pathTemplate: '{{ jp "{.spec.minReplicas}" . }}'
      priority: 3
      type: string
    - name: Max-Replica(s)
      pathTemplate: '{{ jp "{.spec.maxReplicas}" . }}'
      priority: 3
      type: string
    - name: Age
      pathTemplate: '{{ jp "{.metadata.creationTimestamp}" . }}'
      priority: 3
      type: date
```
**HorizontalPodAutoScaler**

```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bb-deployment-test-autoscaler
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bb-deployment-test
  targetCPUUtilizationPercentage: 80
```
